name: First GitHub Actions Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
env:
    app_name: Axion-app
    REGION: ${{ vars.AZURE_REGION }}

permissions:
  contents: read

jobs:
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name:  verify azure login
        run: |
          az account show

      - name: Show Repository Information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Workflow started successfully"
          
      - name: Show information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_SHA"
          echo "$GITHUB_ACTOR"

      - name: Validate Execution
        run: |
          echo "Running validation..."
          test -d .git
          echo "Validation successful"
          
      - name:  Show application name
        run: |
           echo "$app_name"
      - name: Show Azure region
        run: |
           echo "$REGION"

    
