name: First GitHub Actions Workflowv2

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
env:
    app_name: Axion-app
    REGION: ${{ vars.AZURE_REGION }}
    KEYVAULT: ${{ vars.KEYVAULT_NAME }}
    SECRET_NAME: DB-PASSWORD

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name:  verify azure login
        run: |
          az account show

      - name: Retrieve Key Vault Secret
        run: |
          echo "KEYVAULT: $KEYVAULT"
          SECRET_VALUE=$(az keyvault secret show \
            --vault-name "$KEYVAULT" \
            --name "$SECRET_NAME" \
            --query value \
            --output tsv)

          if [ -z "$SECRET_VALUE" ]; then
            echo "Secret value is empty or unavailable"
            exit 1
          fi

          echo "::add-mask::$SECRET_VALUE"
          echo "Secret fetched successfully"

          # Use the secret here without printing it
          export DB_PASSWORD="$SECRET_VALUE"


      - name: Show Repository Information
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Workflow started successfully"
          
      - name: Show information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_SHA"
          echo "$GITHUB_ACTOR"

      - name: Validate Execution
        run: |
          echo "Running validation..."
          test -d .git
          echo "Validation successful"
          
      - name:  Show application name
        run: |
           echo "$app_name"

      - name: Show Azure region
        run: |
           echo "$REGION"



    
